// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVT64SkRvPGvDf442VtRRI1JsUkF_RYs',
    appId: '1:587250402769:web:68291f2d3a877117094cf0',
    messagingSenderId: '587250402769',
    projectId: 'atelier-bfbd1',
    authDomain: 'atelier-bfbd1.firebaseapp.com',
    storageBucket: 'atelier-bfbd1.appspot.com',
    measurementId: 'G-31VD8FSZ5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTvKqB-8N-WZSVQQeH5obbNJZABllqSC8',
    appId: '1:587250402769:android:9b81734711b873ee094cf0',
    messagingSenderId: '587250402769',
    projectId: 'atelier-bfbd1',
    storageBucket: 'atelier-bfbd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrD61t6q0HaZoPWEAHqshBO1XSu35qHo',
    appId: '1:587250402769:ios:16a5f84ab619e875094cf0',
    messagingSenderId: '587250402769',
    projectId: 'atelier-bfbd1',
    storageBucket: 'atelier-bfbd1.appspot.com',
    androidClientId: '587250402769-10utta2l1k904k15ai68k2c6en9uag9n.apps.googleusercontent.com',
    iosClientId: '587250402769-1r425v2o23n1kdgrhv6egavuct24l9mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fltratl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrD61t6q0HaZoPWEAHqshBO1XSu35qHo',
    appId: '1:587250402769:ios:5f7789178b5c256b094cf0',
    messagingSenderId: '587250402769',
    projectId: 'atelier-bfbd1',
    storageBucket: 'atelier-bfbd1.appspot.com',
    androidClientId: '587250402769-10utta2l1k904k15ai68k2c6en9uag9n.apps.googleusercontent.com',
    iosClientId: '587250402769-0qhd0fit999rljq5g46ov8qmpmevursi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fltratl.RunnerTests',
  );
}
